v0.2.1   * [dev] Improved robustness of interal `rreadlinkchain()` function.

diff --git a/bin/rreadlink b/bin/rreadlink
--- a/bin/rreadlink
+++ b/bin/rreadlink
@@ -4,7 +4,7 @@
 
 kTHIS_NAME=${BASH_SOURCE##*/}
 kTHIS_HOMEPAGE='https://github.com/mklement0/rreadlink'
-kTHIS_VERSION='v0.2.0' # NOTE: This assignment is automatically updated by `make version VER=<newVer>` - DO keep the 'v' prefix.
+kTHIS_VERSION='v0.2.1' # NOTE: This assignment is automatically updated by `make version VER=<newVer>` - DO keep the 'v' prefix.
 
 unset CDPATH  # To prevent unexpected `cd` behavior.
 
@@ -99,15 +99,22 @@ esac
 
 ## -------
 # SYNOPSIS
-#   rreadlinkchain symLink
+#   rreadlinkchain <symLink>
 # DESCRIPTION
 #  Recursive readlink: prints the CHAIN OF SYMLINKS from the input
 #  file to its ultimate target, with each path on a separate line.
 #  Only the ultimate target's path is canonical, though.
+#  A broken symlink in the chain causes an error that reports the
+#  non-existent target.
+#  An input path that is not a symlink will print its own canonical path.
+#  
 # NOTES
-#   Attempts to use `readlink`, which is found on most modern platforms (notable exception: HP-UX)
-#   If `readlink` is not available, output from `ls -l` is parsed, which is the only POSIX-compliant
-#   way to determine a symlink's target; caveat: if a filename contains literal ' -> ', this will break.
+#   Attempts to use `readlink`, which is found on most modern platforms
+#   (notable exception: HP-UX). If `readlink` is not available, output from
+#   `ls -l` is parsed, which is the only POSIX-compliant way to determine a 
+#   symlink's target.
+#    Caveat: This will break if a filename contains literal ' -> ' or has 
+#            embedded newlines.
 # EXAMPLES
 #     # Print the symlink chain of the `git` executable in the $PATH.
 #   rreadlinkchain  "$(which git)"
@@ -115,35 +122,44 @@ esac
 #   rreadlinkchain  "$(which git)" | sed -nE -e '$!{a\'$'\n''@ -> ' -e '}; p' | tr -d '\n'
 # THANKS
 #   http://stackoverflow.com/a/1116890/45375
-rreadlinkchain() ( # execute in *subshell* to localize the effect of `cd`
+rreadlinkchain() ( # execute in *subshell* to localize the effect of `cd`, ...
 
-  local target=$1 targetDir targetName readlinkexe=$(command -pv readlink) CDPATH= 
+  local target=$1 targetDir targetName readlinkexe=$(command -v readlink) CDPATH= 
   
+  # Since we'll be using `command` below for a predictable execution
+  # environment, we make sure that it has its original meaning.
+  { \unalias command; \unset -f command; } &>/dev/null
+
   while :; do
-      # Unless the file is a symlink OR exists, we report an error - note that using `-e` with a symlink reports the *target*'s existence, not the symlink's.
-    [[ -L $target || -e $target ]] || { printf '%s\n' "ERROR: $kTHIS_NAME: '$target' does not exist." 1>&2; return 1; }
+      # Unless the file is a symlink OR exists, we report an error - note that 
+      # using `-e` with a symlink reports the *target*'s existence, not the
+      # symlink's.
+    [[ -L $target || -e $target ]] || { command printf '%s\n' "ERROR: $FUNCNAME: '$target' does not exist." 1>&2; return 1; }
       # !! We use `cd` to change to the target's folder
       # !! so we can correctly resolve the full dir. path.
-    builtin cd "$(command -p dirname -- "$target")" # note: cd "" is the same as cd . - i.e., a no-op.
+    command cd "$(command dirname -- "$target")" # note: cd "" is the same as cd . - i.e., a no-op.
     targetDir=$PWD
-    targetName=$(command -p basename -- "$target")
+    targetName=$(command basename -- "$target")
+    [[ $targetName == '/' ]] && targetName='' # !! curiously, `basename /` returns '/'
     done=0
     if [[ ! -L $targetName ]]; then
-        # We've found the ultimate target (or the input file wasn't a symlink to begin with).
-        # For the *ultimate* target we want use `pwd -P` to make sure we use the actual, physical directory,
-        # (not a symlink) to get the *canonical* path.
-      targetDir=$(builtin pwd -P)
+        # We've found the ultimate target (or the input file wasn't a symlink to
+        # begin with). For the *ultimate* target we want use `pwd -P` to make
+        # sure we use the actual, physical directory (not a symlink) to get the
+        # *canonical* path.
+      targetDir=$(command pwd -P)
       done=1
     fi
-      # Print (next) path - note that we manually resolve paths ending in /. and /.. to make sure we have a normalized path.
+      # Print (next) path - note that we manually resolve paths ending in /. 
+      # and /.. to make sure we have a normalized path.
     if [[ $targetName == '.' ]]; then
-      printf '%s\n' "${targetDir%/}"
+      command printf '%s\n' "${targetDir%/}"
     elif  [[ $targetName == '..' ]]; then
-      # Caveat: something like /var/.. will resolve to /private (assuming /var@ -> /private/var), i.e. the '..' is applied
-      # AFTER canonicalization.
-      printf '%s\n' "$(command -p dirname -- "${targetDir}")"
+      # Caveat: something like /var/.. will resolve to /private (assuming
+      # /var@ -> /private/var), i.e. the '..' is applied AFTER canonicalization.
+      command printf '%s\n' "$(command dirname -- "${targetDir}")"
     else
-      printf '%s\n' "${targetDir%/}/$targetName"
+      command printf '%s\n' "${targetDir%/}/$targetName"
     fi
       # Exit, if we've hit the non-symlink at the end of the chain.
     (( done )) && break 
@@ -151,9 +167,10 @@ rreadlinkchain() ( # execute in *subshell* to localize the effect of `cd`
     if [[ -n $readlinkexe ]]; then # Use `readlink`.
       target=$("$readlinkexe" -- "$targetName")
     else # `readlink` utility not available.
-      # Parse `ls -l` output, which, unfortunately, is the only POSIX-compliant way
-      # to determine a symlink's target. Hypothetically, this can break with filenames containig literal ' ->'.
-      target=$(command -p ls -l -- "$targetName")
+      # Parse `ls -l` output, which, unfortunately, is the only POSIX-compliant 
+      # way to determine a symlink's target. Hypothetically, this can break with
+      # filenames containig literal ' -> ' and embedded newlines.
+      target=$(command ls -l -- "$targetName")
       target=${target#* -> }
     fi
   done
